const PRODUCTS_LIST_FETCH_REQUESTED = 'PRODUCTS_LIST_FETCH_REQUESTED';
const PRODUCTS_LIST_FETCH_SUCCEEDED = 'PRODUCTS_LIST_FETCH_SUCCEEDED';
const PRODUCTS_LIST_FETCH_FAILED = 'PRODUCTS_LIST_FETCH_FAILED';

const PRODUCT_FETCH_REQUESTED = 'PRODUCT_FETCH_REQUESTED';
const PRODUCT_FETCH_SUCCEEDED = 'PRODUCT_FETCH_SUCCEEDED';
const PRODUCT_FETCH_FAILED = 'PRODUCT_FETCH_FAILED';

export default {
  PRODUCTS_LIST_FETCH_REQUESTED,
  PRODUCTS_LIST_FETCH_SUCCEEDED,
  PRODUCTS_LIST_FETCH_FAILED,

  PRODUCT_FETCH_REQUESTED,
  PRODUCT_FETCH_SUCCEEDED,
  PRODUCT_FETCH_FAILED,
};
