const PRODUCTS_FETCH_REQUESTED = 'PRODUCTS_FETCH_REQUESTED';
const PRODUCTS_FETCH_SUCCEEDED = 'PRODUCTS_FETCH_SUCCEEDED';
const PRODUCTS_FETCH_FAILED = 'PRODUCTS_FETCH_FAILED';

export default {
  PRODUCTS_FETCH_REQUESTED,
  PRODUCTS_FETCH_SUCCEEDED,
  PRODUCTS_FETCH_FAILED,
};
